---
title: "Playground"
author: "Henry Traynor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Playground}
# script for messing with code and developing new functions/figures

SIRS_parms  <- c(beta = 0.01, #transmission rate
                 gamma = 0.07, #recovery rate (14 day inf)
                 mu = 0.0055) # waning immunity (180 day immunity)

roost_parms <- c(num_roosts = 10,  # number of roosts
                 num_clusters = 2, # number of clusters
                 sd = 0.05)           # standard distance from cluster center

roost_map <- roostMap(roost_parms)
roost_dist <- distMatrix(roost_parms[1], roost_map)

library(ggplot2)
ggplot(roost_map, aes(x,y, color=bin, label = lbl, size=N_max)) + geom_text() + xlim(0,1) + ylim(0,1)
```


```{r Roosts}
roosts <- data.frame(
  S = vector("numeric", length=roost_parms[1]),
  I = vector("numeric", length=roost_parms[1]),
  R = vector("numeric", length=roost_parms[1]),
  N = vector("numeric", length=roost_parms[1]),
  N_max = roost_map$N_max
)

#Populate Roosts
roosts$N <- round(roosts$N_max/1.5)
roosts$S <- roosts$N
roosts$S[1] <- roosts$S[1]-1
roosts$S[2] <- roosts$S[2]-1
roosts$S[3] <- roosts$S[3]-1
roosts$I <- roosts$N-roosts$S

#Total distances between any 2 roosts
total_dist <- 0
for(i in 1:roost_parms[1]) {
  for(j in 1:i) {
    total_dist <- total_dist + as.numeric(roost_dist[i,j])
  }
}

#Score, a measure of isolation. greater score ==> greater isolation
scores <- vector("numeric", length=roost_parms[1])
for(i in 1:roost_parms[1]) {
  tot <- sum(roost_dist[i,])
  scores[i] <- tot/total_dist
}
```


```{r Leap}
#SIRSleap test
SIRS_list <- list()
SIRS_list[[1]] <- roosts[1,]
for(i in 2:1000) {
  SIRS_list[[i]] <- SIRSleap(SIRS_list[[i-1]],
                             SIRS_parms)
}
svec <- c()
for(i in 1:length(SIRS_list)) {
  svec[i] <- SIRS_list[[i]]$R
}
svec

#daytime rest
SIRS_list <- list()
SIRS_list[[1]] <- roosts
for(i in 2:1000) {
  SIRS_list[[i]] <- daytime(SIRS_list[[i-1]],
                            roost_parms,
                            SIRS_parms,
                            model="SIRS")
}

#singleDay test
SIRS_list <- list()
SIRS_list[[1]] <- roosts
for(i in 2:1000) {
  SIRS_list[[i]] <- singleDay(SIRS_list[[i-1]],
                              roost_dist,
                              roost_parms,
                              SIRS_parms,
                              model="SIRS",
                              scores,
                              phi_max=0.25)
}

svec <- list()
for(i in 1:length(SIRS_list)) {
  svec[[i]] <-  SIRS_list[[i]][1,1:4]
}
svec
```