---
title: "Stochastic Measure"
author: "Henry Traynor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

How stochastic is our model?
We want to create a set of realizations with a single set of parameters and examine the differences in system behavior.

First, we create a roost map.

```{r}
SIR_parms  <- c(beta = 0.05, #transmission rate
                gamma = 0.03) # recovery rate

roost_parms <- c(num_roosts = 10,  # number of roosts
                 num_clusters = 3, # number of clusters
                 sd = 0.1)           # standard distance from cluster center

source("Functions/roost_map.R")

roost_map <- roostMap(roost_parms)
roost_dist <- distMatrix(roost_parms[1], roost_map)

library(ggplot2)
ggplot(roost_map, aes(x,y, color=bin, label = lbl, size=N_max)) + geom_text() + xlim(0,1) + ylim(0,1)
```

```{r}
roosts <- data.frame(
  S = vector("numeric", length=roost_parms[1]),
  I = vector("numeric", length=roost_parms[1]),
  R = vector("numeric", length=roost_parms[1]),
  N = vector("numeric", length=roost_parms[1]),
  N_max = roost_map$N_max
)

#Populate Roosts
roosts$N <- round(roosts$N_max/2)
roosts$S <- roosts$N
roosts[1,1:2] <- c(roosts$S[1]-1,1)

#Total distances between any 2 roosts
total_dist <- 0
for(i in 1:roost_parms[1]) {
  for(j in 1:i) {
    total_dist <- total_dist + as.numeric(roost_dist[i,j])
  }
}

#Score, a measure of isolation. greater score ==> greater isolation
scores <- vector("numeric", length=roost_parms[1])
for(i in 1:roost_parms[1]) {
  tot <- sum(roost_dist[i,])
  scores[i] <- tot/total_dist
}
```

Next, we create a set of realizations and record values for a single roost.

```{r}
source("Functions/single_day.R")
roost_series_series <- list()

num_realizations <- 10
num_days <- 150
roost_index <- 2

for(i in 1:num_realizations) {
  roost_series <- list()
  roost_series[[1]] <- roosts
  for(j in 2:num_days) {
    roost_series[[j]] <- singleDay(roost_series[[j-1]],
                                   roost_dist,
                                   roost_parms, 
                                   SIR_parms, 
                                   scores)
  }
  roost_series_series[[i]] <- roost_series
}

single_roost_series <- list()
for(i in 1:num_realizations) {
  df <- data.frame(time = seq(1,num_days),
                   S = vector("numeric", num_days),
                   I = vector("numeric", num_days),
                   R = vector("numeric", num_days),
                   N = vector("numeric", num_days))
  for(j in 1:num_days) {
    df[j,2:5] <- roost_series_series[[i]][[j]][roost_index,1:4]
  }
  single_roost_series[[i]] <- df
}

library(dplyr)
#choose variable of interest
title <- paste0("10 Realizations of the Model: Roost ",roost_index)
graph <- ggplot(bind_rows(single_roost_series, .id="data_frame"),
                aes(time, N, color=data_frame)) +
  geom_line() +
  ggtitle(title) +
  guides(color = guide_legend(title = "Realization")) 


print(graph)
```

