---
title: "BubbleMap_Gen"
author: "Henry Traynor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
SIR_parms  <- c(beta = 0.05, #transmission rate
                gamma = 0.03) # recovery rate

SIRS_parms  <- c(beta = 0.05, #transmission rate
                gamma = 0.03,
                omega = 0.01) # recovery rate for 180 day mean immunity

roost_parms <- c(num_roosts = 10,  # number of roosts
                 num_clusters = 4, # number of clusters
                 sd = 0.2, #avg distance from roost cluster
                 avg_N_max = 50, # roost size upper bound
                 min_N_max = 5) #minimum roost size
library(truncnorm)
roost_map <- roostMap(roost_parms)
roost_dist <- distMatrix(roost_parms[1], roost_map)

library(ggplot2)
ggplot(roost_map, aes(x,y, color=bin, label = lbl, size=N_max)) + geom_text() + xlim(0,1) + ylim(0,1)
```

```{r}
roosts <- data.frame(
  S = vector("numeric", length=roost_parms[1]),
  I = vector("numeric", length=roost_parms[1]),
  R = vector("numeric", length=roost_parms[1]),
  N = vector("numeric", length=roost_parms[1]),
  N_max = roost_map$N_max
)

#Populate Roosts
roosts$N <- round(roosts$N_max/2)
roosts$S <- roosts$N
roosts[1,1:2] <- c(roosts$S[1]-1,1)

#Total distances between any 2 roosts
total_dist <- 0
for(i in 1:roost_parms[1]) {
  for(j in 1:i) {
    total_dist <- total_dist + as.numeric(roost_dist[i,j])
  }
}

#Score, a measure of isolation. greater score ==> greater isolation
scores <- vector("numeric", length=roost_parms[1])
for(i in 1:roost_parms[1]) {
  tot <- sum(roost_dist[i,])
  scores[i] <- tot/total_dist
}
```

```{r}
roost_series_series <- list()

num_realizations <- 10
num_days <- 600
roost_index <- 4

for(i in 1:num_realizations) {
  roost_series <- list()
  roost_series[[1]] <- roosts
  for(j in 2:num_days) {
    roost_series[[j]] <- singleDay(roost_series[[j-1]],
                                   roost_dist,
                                   roost_parms, 
                                   SIRS_parms,
                                   model="SIRS",
                                   scores)
  }
  roost_series_series[[i]] <- roost_series
}
```

```{r}
mean_intensity <- Reduce(
  "+",
  lapply(roost_series_series, function(rep) {
    Reduce("+", lapply(rep, function(day) day$I))
  })
) / length(roost_series_series)

mean_intensity_normalized <- mean_intensity / roost_series_series[[1]][[1]]$N_max
```

```{r}
roost_map_intensity <- roost_map
roost_map_intensity$intensity <- mean_intensity
roost_map_intensity$normalized <- mean_intensity_normalized
roost_map_intensity$log_intensity <- log1p(roost_map_intensity$intensity)
```

```{r}
library(ggplot2)
library(ggrepel)

ggplot() +
  # All OTHER roosts
  geom_point(
    data = subset(roost_map_intensity, lbl != 1),
    aes(x = x, y = y,
        size = intensity,
        fill = normalized),
    shape = 21,
    color = "black",
    alpha = 0.85
  ) +
  
  # ROOST 1 (green border)
  geom_point(
    data = subset(roost_map_intensity, lbl == 1),
    aes(x = x, y = y,
        size = intensity,
        fill = normalized),
    shape = 21,
    color = "green",
    stroke = 1.5,   # thicker border
    alpha = 0.85
  ) +
  
  geom_text_repel(
    data = roost_map,
    aes(x = x, y = y, label = N_max),
    size = 3
  ) +
  
  scale_size_area(max_size = 14) +
  scale_fill_viridis_c(option = "magma") +
  coord_equal() +
  theme_minimal(base_size = 14) +
  labs(
    size = "Cumulative Intensity",
    fill = "Relative Intensity",
    title = "Mean Epidemic Intensity Across Roosts"
  )
```
