---
title: "N_max Distribution"
author: "Henry Traynor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Sourcing}
files_functions <- list.files(path = "C:/Users/henry/Molossid_Transmission/Functions", pattern = "\\.R$", full.names = TRUE)
for(file in files_functions) {
  source(file)
}
```

```{r Parameters}
#Define SIR Model Parameters
SIR_parms  <- c(beta = 0.1, #transmission rate
                gamma = 0.03) # recovery rate

roost_parms <- c(num_roosts = 25,  # number of roosts
                 num_clusters = 5, # number of clusters
                 sd = 0.05, #avg distance from roost cluster
                 avg_N_max = 70, # roost size upper bound
                 min_N_max = 10) #minimum roost size
```

```{r Roost Creation}
roost_map <- roostMap(roost_parms)
roost_dist <- distMatrix(roost_parms[1], roost_map)

library(ggplot2)
ggplot(roost_map, aes(x,y, color=bin, label = lbl, size=N_max)) + geom_text() + xlim(0,1) + ylim(0,1)
```


```{r Roosts}
roosts <- data.frame(
  S = vector("numeric", length=roost_parms[1]),
  I = vector("numeric", length=roost_parms[1]),
  R = vector("numeric", length=roost_parms[1]),
  N = vector("numeric", length=roost_parms[1]),
  N_max = roost_map$N_max
)

scores <- function(num_roosts, roost_dist) {
  total_dist <- 0
  for(i in 1:num_roosts) {
    for(j in 1:i) {
      total_dist <- total_dist + as.numeric(roost_dist[i,j])
    }
  }
  vec <- vector("numeric", length=roost_parms[1])
  for(i in 1:num_roosts) {
    tot <- sum(roost_dist[i,])
    vec[i] <- tot/total_dist
  }
  return(vec)
}
```


```{r Distributions}
# Explore effects of sampling from varying statistical distributions for N_max
distributions <- c("Normal", "Poisson", "Uniform", "Gamma", "Geometric", "Linear inc.", "Linear dec.")
N_max_list <- list()

avg_occ <- 50

library(triangle)

N_max_list[["Normal"]] <- round(rnorm(roost_parms["num_roosts"], avg_occ, sd=5))
N_max_list[["Poisson"]] <- rpois(roost_parms["num_roosts"], avg_occ)
N_max_list[["Uniform"]] <- round(runif(roost_parms["num_roosts"], min=10, max=90))
N_max_list[["Gamma"]] <- round(rgamma(roost_parms["num_roosts"], avg_occ))
N_max_list[["Geometric"]] <- rgeom(roost_parms["num_roosts"], 1/avg_occ)
N_max_list[["Linear inc."]] <- rtriangle(roost_parms["num_roosts"], a=10, b=90, c=90)
N_max_list[["Linear dec."]] <- rtriangle(roost_parms["num_roosts"], a=10, b=90, c=10)

num_realizations <- 10
num_days <- 50

df_dist <- data.frame(distribution = vector(),
                      peak_index = numeric(),
                      peak_prop = numeric())

for(real in 1:num_realizations) {
  for(dist in distributions) {
    
    # Generate roost map and distances
    roost_map <- roostMap(roost_parms)
    roost_dist <- distMatrix(roost_parms["num_roosts"], roost_map)
    
    # Compute scores
    total_dist <- sum(roost_dist[upper.tri(roost_dist, diag = TRUE)])
    scores <- numeric(roost_parms["num_roosts"])
    for(i in 1:roost_parms["num_roosts"]) {
      scores[i] <- sum(roost_dist[i, ]) / total_dist
    }
    
    # Initialize roosts with updated N_max vector
    roost_map$N_max = N_max_list[[dist]]
    roosts <- data.frame(
      S = round(roost_map$N_max / 1.5),
      I = 0,
      R = 0,
      N = round(roost_map$N_max / 1.5),
      N_max = roost_map$N_max
    )
    roosts$S[1] <- roosts$S[1] - 1
    roosts$I[1] <- 1
    
    # Run simulation
    temp <- list()
    temp[[1]] <- roosts
    for(day in 2:num_days) {
      temp[[day]] <- singleDay(
        roosts = temp[[day - 1]],
        roost_dist = roost_dist,
        roost_parms = roost_parms,
        inf_parms = SIR_parms,
        model = "SIR",
        scores = scores,
        phi_max = 0.25
      )
    }
    
    # Compute peak
    prop_inf <- sapply(temp, function(x) sum(x$I) / sum(x$N))
    peak_index <- which.max(prop_inf)
    peak_prop <- max(prop_inf)
    
    df_dist <- rbind(df_dist, data.frame(distribution = dist,
                                         peak_index = peak_index,
                                         peak_prop = peak_prop))
  }
}

```

```{r Summary}
# Summarize mean ± SD
df_summary <- df_dist %>%
  group_by(distribution) %>%
  summarise(
    mean_peak_index = mean(peak_index, na.rm = TRUE),
    sd_peak_index = sd(peak_index, na.rm = TRUE),
    mean_peak_prop = mean(peak_prop, na.rm = TRUE),
    sd_peak_prop = sd(peak_prop, na.rm = TRUE)
  )
```

```{r Summary Plot}
prop_summary_plot <- ggplot(df_summary, aes(x = distribution, y = mean_peak_prop)) +
  geom_col(fill = "skyblue", color = "black", width = 0.6) +
  geom_errorbar(aes(ymin = mean_peak_prop - sd_peak_prop, ymax = mean_peak_prop + sd_peak_prop), 
                width = 0.2, linewidth = 0.8) +
  labs(x = "Distribution", y = "Mean peak prop. ± SD") +
  theme_minimal(base_size = 14)

index_summary_plot <- ggplot(df_summary, aes(x = distribution, y = mean_peak_index)) +
  geom_col(fill = "skyblue", color = "black", width = 0.6) +
  geom_errorbar(aes(ymin = mean_peak_index - sd_peak_index, ymax = mean_peak_index + sd_peak_index), 
                width = 0.2, linewidth = 0.8) +
  labs(x = "Distribution", y = "Mean peak index ± SD") +
  theme_minimal(base_size = 14)

#prep N_max list for plotting
df_dist_vis <- data.frame(distribution = vector(),
                          x = numeric(),
                          probability = numeric())

for(x in 1:100) {
  df_dist_vis <- rbind(df_dist_vis, c("Normal", x, dnorm(x, mean=avg_occ, sd=5)))
  df_dist_vis <- rbind(df_dist_vis, c("Poisson", x, dpois(x, avg_occ)))
  df_dist_vis <- rbind(df_dist_vis, c("Uniform", x, dunif(x, min=10, max=90)))
  df_dist_vis <- rbind(df_dist_vis, c("Gamma", x, dgamma(x, shape=avg_occ)))
  df_dist_vis <- rbind(df_dist_vis, c("Geometric", x, dgeom(x, 1/avg_occ)))
  df_dist_vis <- rbind(df_dist_vis, c("Linear inc.", x, dtriangle(x, a=1, b=100, c=100)))
  df_dist_vis <- rbind(df_dist_vis, c("Linear dec.", x, dtriangle(x, a=1, b=100, c=1)))
}
colnames(df_dist_vis) <- c("distribution", "N_max", "probability")
df_dist_vis$N_max <- as.numeric(df_dist_vis$N_max)
df_dist_vis$probability <- as.numeric(df_dist_vis$probability)

dist_prob_plot <- ggplot(df_dist_vis, aes(x = N_max, y = probability, color = distribution, group = distribution)) +
  geom_line(size = 1) +
  scale_x_continuous(
    name = "N_max",
    breaks = pretty(df_dist_vis$N_max, n = 5)   # ~5 evenly spaced tick marks
  ) +
  scale_y_continuous(
    name = "Probability",
    breaks = pretty(df_dist_vis$probability, n = 5)
  ) +
  labs(color = "Distribution") +
  theme_minimal(base_size = 14)

grid.arrange(prop_summary_plot, index_summary_plot, dist_prob_plot)
```
