---
title: "Epidemic Speed"
author: "Henry Traynor"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Sourcing}
files_functions <- list.files(path = "C:/Users/henry/Molossid_Transmission/Functions", pattern = "\\.R$", full.names = TRUE)
for(file in files_functions) {
  source(file)
}
```

```{r Parameters}
#Define SIR Model Parameters
SIR_parms  <- c(beta = 0.1, #transmission rate
                gamma = 0.03) # recovery rate

roost_parms <- c(num_roosts = 25,  # number of roosts
                 num_clusters = 20, # number of clusters
                 sd = 0.05, #avg distance from roost cluster
                 avg_N_max = 70, # roost size upper bound
                 min_N_max = 10) #minimum roost size
```

```{r Roost Creation}
roost_map <- roostMap(roost_parms)
roost_dist <- distMatrix(roost_parms[1], roost_map)

library(ggplot2)
ggplot(roost_map, aes(x,y, color=bin, label = lbl, size=N_max)) + geom_text() + xlim(0,1) + ylim(0,1)
```


```{r Roosts}
roosts <- data.frame(
  S = vector("numeric", length=roost_parms[1]),
  I = vector("numeric", length=roost_parms[1]),
  R = vector("numeric", length=roost_parms[1]),
  N = vector("numeric", length=roost_parms[1]),
  N_max = roost_map$N_max
)

#Populate Roosts
roosts$N <- round(roosts$N_max/1.5)
roosts$S <- roosts$N
roosts$S[1] <- roosts$S[1]-1
roosts$I <- roosts$N-roosts$S

calc_scores <- function(num_roosts, roost_dist) {
  total_dist <- 0
  for(i in 1:num_roosts) {
    for(j in 1:i) {
      total_dist <- total_dist + as.numeric(roost_dist[i,j])
    }
  }
  vec <- vector("numeric", length=roost_parms[1])
  for(i in 1:num_roosts) {
    tot <- sum(roost_dist[i,])
    vec[i] <- tot/total_dist
  }
  return(vec)
}
```

```{r Compute and Store Realizations}
series_list <- list()
num_days <- 50
max_clusters <- 3

#Total distances between any 2 roosts
total_dist <- 0
for(i in 1:roost_parms[1]) {
  for(j in 1:i) {
    total_dist <- total_dist + as.numeric(roost_dist[i,j])
  }
}
#Score, a measure of isolation. greater score ==> greater isolation
scores <- vector("numeric", length=roost_parms[1])
for(i in 1:roost_parms[1]) {
  tot <- sum(roost_dist[i,])
  scores[i] <- tot/total_dist
}

for(i in 1:max_clusters) {
  temp <- list()
  temp[[1]] <- roosts
  for(j in 2:num_days) {
    roost_parms["num_clusters"] <- i
    temp[[j]] <- singleDay(temp[[j-1]],
                           roost_dist,
                           roost_parms,
                           SIR_parms,
                           "SIR",
                           scores,
                           phi_max=0.25)
  }
  series_list[[i]] <- temp
}
```

```{r Extraction}
df_peak <- data.frame(num_clusters = seq(1:max_clusters),
                      peak_index = vector(mode="integer", length=max_clusters),
                      peak_prop = vector(mode="numeric", length=max_clusters))
                   
for(i in 1:length(series_list)) {
  temp <- c()
  for(k in 1:length(series_list[[i]])) {
    temp[k] <- sum(series_list[[i]][[k]]$I)/sum(series_list[[i]][[k]]$N)
  }
  df_peak$peak_index[i] <- which.max(temp)
  df_peak$peak_prop[i] <- temp[which.max(temp)]
}
```

```{r Plot}
library(ggplot2)
library(gridExtra)
p <- ggplot(data=df_peak,
            aes(x=num_clusters, y=peak_prop)) + geom_line()
g <- ggplot(data=df_peak,
            aes(x=num_clusters, y=peak_index)) + geom_line()
grid.arrange(p,g)
```

```{r Now with average/sd values}
num_realizations=10 # number of realizations per number of clusters
num_days <- 50 # length of each time series (days)
max_clusters <- 20 #max number of clusters

# df to store data
df_peak <- data.frame(num_clusters = integer(),
                      peak_index = integer(),
                      peak_prop = numeric())

for(i in 1:num_realizations) {
  #empty list
  series_list <- list()
  for(p in 1:max_clusters) {
    temp <- list() # temporary storage vector
    temp[[1]] <- roosts # populate initial conditions
    
    roost_parms["num_clusters"] <- p # update num_clusters
    roost_map <- roostMap(roost_parms) # update roost map
    roost_dist <- distMatrix(roost_parms["num_roosts"], roost_map) # update dist matrix
    
    
    #Total distances between any 2 roosts
    total_dist <- 0
    for(k in 1:roost_parms[1]) {
      for(j in 1:k) {
        total_dist <- total_dist + as.numeric(roost_dist[k,j])
      }
    }
    #Score, a measure of isolation. greater score ==> greater isolation
    scores <- vector("numeric", length=roost_parms[1])
    for(k in 1:roost_parms[1]) {
      tot <- sum(roost_dist[k,])
      scores[k] <- tot/total_dist
    }
    
    for(q in 2:num_days) { 
      # populate remaining iterations in temp
      temp[[q]] <- singleDay(temp[[q-1]],
                            roost_dist,
                            roost_parms,
                            SIR_parms,
                            "SIR",
                            scores,
                            phi_max=0.25)
    }
    # add to list
    series_list[[p]] <- temp
  }
  
  for(r in 1:length(series_list)) {
    temp <- c()
    for(k in 1:length(series_list[[r]])) {
      # compute proportion of infected individuals
      temp[k] <- sum(series_list[[r]][[k]]$I)/sum(series_list[[r]][[k]]$N)
    }
    # vector to be added to df_peak
    bindvec <- c(num_clusters = r,
                 peak_index = which.max(temp),
                 peak_prop = temp[which.max(temp)])
    
    df_peak <- rbind(df_peak, bindvec)
  }
}
colnames(df_peak) <- c("num_clusters", "peak_index", "peak_prop")

# now we calculate average peak index and peak proportion by number of clusters. store with standard deviation

library(dplyr) 
df_summary <- df_peak %>%
  group_by(num_clusters) %>%
  summarise(
    mean_peak_index = mean(peak_index, na.rm = TRUE),
    sd_peak_index   = sd(peak_index, na.rm = TRUE),
    mean_peak_prop  = mean(peak_prop, na.rm = TRUE),
    sd_peak_prop    = sd(peak_prop, na.rm = TRUE)
  )

```

```{r Summary Plot}
library(gridExtra)
prop_summary_plot <- ggplot(df_summary, aes(x=num_clusters, y=mean_peak_prop)) +
  geom_point(size=3) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_peak_prop - sd_peak_prop,
                    ymax = mean_peak_prop + sd_peak_prop),
                width = 0.2) +
  labs(x = "Number of clusters",
       y = "Average peak proportion ± 1 SD") +
  theme_minimal() 

index_summary_plot <- ggplot(df_summary, aes(x=num_clusters, y=mean_peak_index)) +
  geom_point(size=3) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_peak_index - sd_peak_index,
                    ymax = mean_peak_index + sd_peak_index),
                width = 0.2) +
  labs(x = "Number of clusters",
       y = "Average peak index ± 1 SD") +
  theme_minimal()

grid.arrange(prop_summary_plot,
             index_summary_plot)
```

```{r SD Variation Setup}
library(dplyr)
library(ggplot2)
library(gridExtra)

num_realizations <- 10
num_days <- 50
sd_values <- seq(0.01, 0.1, by = 0.01)  # sequence of cluster SDs to explore

# Data frame to store results
df_peak <- data.frame(
  sd = numeric(),
  peak_index = integer(),
  peak_prop = numeric()
)

for(real in 1:num_realizations) {
  for(sd_val in sd_values) {
    
    # Update roost parameters
    local_roost <- roost_parms
    local_roost["sd"] <- sd_val
    
    # Generate roost map and distances
    roost_map <- roostMap(local_roost)
    roost_dist <- distMatrix(local_roost["num_roosts"], roost_map)
    
    # Compute scores
    total_dist <- sum(roost_dist[upper.tri(roost_dist, diag = TRUE)])
    scores <- numeric(local_roost["num_roosts"])
    for(i in 1:local_roost["num_roosts"]) {
      scores[i] <- sum(roost_dist[i, ]) / total_dist
    }
    
    # Initialize roosts
    roosts <- data.frame(
      S = round(roost_map$N_max / 1.5),
      I = 0,
      R = 0,
      N = round(roost_map$N_max / 1.5),
      N_max = roost_map$N_max
    )
    roosts$S[1] <- roosts$S[1] - 1
    roosts$I[1] <- 1
    
    # Run simulation
    temp <- list()
    temp[[1]] <- roosts
    for(day in 2:num_days) {
      temp[[day]] <- singleDay(
        roosts = temp[[day - 1]],
        roost_dist = roost_dist,
        roost_parms = local_roost,
        inf_parms = SIR_parms,
        model = "SIR",
        scores = scores,
        phi_max = 0.25
      )
    }
    
    # Compute peak
    prop_inf <- sapply(temp, function(x) sum(x$I) / sum(x$N))
    peak_index <- which.max(prop_inf)
    peak_prop <- max(prop_inf)
    
    df_peak <- rbind(df_peak, data.frame(sd = sd_val,
                                         peak_index = peak_index,
                                         peak_prop = peak_prop))
  }
}
```

```{r SD Summary}
# Summarize mean ± SD
df_summary <- df_peak %>%
  group_by(sd) %>%
  summarise(
    mean_peak_index = mean(peak_index, na.rm = TRUE),
    sd_peak_index = sd(peak_index, na.rm = TRUE),
    mean_peak_prop = mean(peak_prop, na.rm = TRUE),
    sd_peak_prop = sd(peak_prop, na.rm = TRUE)
  )
```

```{r SD Summary Plot}
prop_summary_plot <- ggplot(df_summary, aes(x = sd, y = mean_peak_prop)) +
  geom_point(size = 3) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_peak_prop - sd_peak_prop,
                    ymax = mean_peak_prop + sd_peak_prop),
                width = 0.002) +
  labs(x = "Roost cluster SD",
       y = "Average peak proportion ± 1 SD") +
  theme_minimal()

index_summary_plot <- ggplot(df_summary, aes(x = sd, y = mean_peak_index)) +
  geom_point(size = 3) +
  geom_line() +
  geom_errorbar(aes(ymin = mean_peak_index - sd_peak_index,
                    ymax = mean_peak_index + sd_peak_index),
                width = 0.002) +
  labs(x = "Roost cluster SD",
       y = "Average peak index ± 1 SD") +
  theme_minimal()

grid.arrange(prop_summary_plot, index_summary_plot)
```



